package com.chord_notes_app.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF86243C)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFB5485F)
val onPrimaryContainerLight = Color(0xFFFFFFFF)
val secondaryLight = Color(0xFF844F58)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFFFC3CB)
val onSecondaryContainerLight = Color(0xFF5F3038)
val tertiaryLight = Color(0xFF713C00)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFA55A00)
val onTertiaryContainerLight = Color(0xFFFFFFFF)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFFF8F7)
val onBackgroundLight = Color(0xFF031C30)
val surfaceLight = Color(0xFFFFF8F7)
val onSurfaceLight = Color(0xFF23191A)
val surfaceVariantLight = Color(0xFFF9DBDE)
val onSurfaceVariantLight = Color(0xFF564244)
val outlineLight = Color(0xFF897174)
val outlineVariantLight = Color(0xFFDCC0C2)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF392D2F)
val inverseOnSurfaceLight = Color(0xFFFFECED)
val inversePrimaryLight = Color(0xFFFFB2BD)
val surfaceDimLight = Color(0xFFE9D6D7)


val primaryDark = Color(0xFFFFB2BD)
val onPrimaryDark = Color(0xFF640725)
val primaryContainerDark = Color(0xFFAA3F56)
val onPrimaryContainerDark = Color(0xFFFFFFFF)
val secondaryDark = Color(0xFFF9B5BE)
val onSecondaryDark = Color(0xFF4F232B)
val secondaryContainerDark = Color(0xFF5E2F38)
val onSecondaryContainerDark = Color(0xFFFFC2CA)
val tertiaryDark = Color(0xFFFFB77B)
val onTertiaryDark = Color(0xFF4D2700)
val tertiaryContainerDark = Color(0xFF985200)
val onTertiaryContainerDark = Color(0xFFFFFFFF)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF1A1112)
val onBackgroundDark = Color(0xFFF1DEDF)
val surfaceDark = Color(0xFF1A1112)
val onSurfaceDark = Color(0xFFF1DEDF)
val surfaceVariantDark = Color(0xFF564244)
val onSurfaceVariantDark = Color(0xFFDCC0C2)
val outlineDark = Color(0xFFA48B8D)
val outlineVariantDark = Color(0xFF564244)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFF1DEDF)
val inverseOnSurfaceDark = Color(0xFF392D2F)
val inversePrimaryDark = Color(0xFFA23951)



